import paramiko, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
c = paramiko.SSHClient(); c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect('192.168.1.55', 22, 'root', 'Chinaunicom@1358', timeout=15)
def run(cmd):
    i,o,e = c.exec_command(cmd); return (o.read().decode('utf-8','ignore')+e.read().decode('utf-8','ignore')).strip()
print('== index.html mtime ==')
print(run('ls -l --time-style=full-iso /opt/nams-ui/dist/index.html'))
print('== nginx -t ==')
print(run('nginx -t 2>&1'))
print('== curl 首页 ==')
print(run("curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1/"))
print('== curl /prod-api/actuator/health ==')
print(run("curl -s http://127.0.0.1/prod-api/actuator/health"))
print('== dist 里 contact chunk 是否存在 ==')
print(run("ls /opt/nams-ui/dist/static/js/ | grep -i contact || echo 'no contact chunk'"))
print('== app.js 是否含 contactOptions / pushplus-token ==')
print(run("grep -l 'contactOptions' /opt/nams-ui/dist/static/js/*.js | head -3"))
print(run("grep -o 'pushplus-token' /opt/nams-ui/dist/static/js/app.*.js | head -1"))
c.close()
